allowBuilds:
  '@parcel/watcher': true
  esbuild: true
  unrs-resolver: true
minimumReleaseAgeExclude:
  - vrchat@2.24.0
  - '@book000/*'
patchedDependencies:
  vrchat@2.24.0: patches/vrchat@2.24.0.patch
